version: '3.8'

services:
  gimmie:
    image: yourbr0ther/gimmie:latest
    ports:
      - "5010:5010"
    volumes:
      - gimmie_data:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - LOGIN_PASSWORD=${LOGIN_PASSWORD:-changeme}
      - DATABASE_URL=sqlite:////app/data/gimmie.db
    networks:
      - gimmie_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/api/items?health=1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  gimmie_network:
    driver: overlay
    attachable: true

volumes:
  gimmie_data:
    driver: local